source 'https://rubygems.org'

# Specify your gem's dependencies in cocoapods-pt.gemspec
gemspec

group :development do
  gem 'cocoapods'

  gem 'mocha'
  gem 'bacon'
  gem 'mocha-on-bacon'
  gem 'prettybacon'
end
